name: yx_scope_linter
description: A package that contains static analysis rules for yx_scope DI framework
version: 0.1.1
repository: 'https://github.com/yandex/yx_scope/tree/main/packages/yx_scope_linter'
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  analyzer: ^5.13.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.5.3
  yx_scope: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
