name: yx_scope_flutter
description: An adapter package that provides yx_scope widgets for Flutter UI integration
version: 1.0.2
repository: https://github.com/yandex/yx_scope
publish_to: 'none'
topics:
  - di
  - scope
  - dependency-injection
  - dependency-management

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  yx_scope: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
